/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/contests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contests */
        get: operations["list_contests_api_v1_admin_contests_get"];
        put?: never;
        /** Create Contest */
        post: operations["create_contest_api_v1_admin_contests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contests/{contest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Contest
         * @description 改场次设置。只改传了的字段。
         *
         *     ``default_roster_id`` 有个特殊之处：``None`` 没法区分"没传"和"要清空"。
         *     所以清空要靠 ``clear_default_roster`` 这个显式开关 —— 否则教师一次选错
         *     名单就再也改不回来了。
         */
        patch: operations["update_contest_api_v1_admin_contests__contest_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/contests/{contest_id}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_api_v1_admin_contests__contest_id__agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contests/{contest_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["list_assets_api_v1_admin_contests__contest_id__assets_get"];
        put?: never;
        /**
         * Upload Asset
         * @description 上传一个待下发文件。
         *
         *     走与服务端回收同一套内容寻址存储：相同内容只占一份磁盘。因此"给全场下发
         *     同一份 500MB 测试点"实际只消耗 500MB，而不是 50 × 500MB。
         */
        post: operations["upload_asset_api_v1_admin_contests__contest_id__assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contests/{contest_id}/deploys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deploys */
        get: operations["list_deploys_api_v1_admin_contests__contest_id__deploys_get"];
        put?: never;
        /**
         * Create Deploy
         * @description 创建下发任务。
         *
         *     注意这里**只建任务**，不推送。Agent 会在下一次 tick 里自己领走 ——
         *     轮询架构下服务端没有"推"这个动作，这也意味着离线机器重连后会自动补上。
         */
        post: operations["create_deploy_api_v1_admin_contests__contest_id__deploys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contests/{contest_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_admin_contests__contest_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contests/{contest_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Files */
        get: operations["list_files_api_v1_admin_contests__contest_id__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contests/{contest_id}/judge/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rescan Judge Results
         * @description 立即重扫成绩目录（忽略 mtime 缓存）。
         */
        post: operations["rescan_judge_results_api_v1_admin_contests__contest_id__judge_rescan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contests/{contest_id}/judge/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Judge Runs */
        get: operations["list_judge_runs_api_v1_admin_contests__contest_id__judge_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contests/{contest_id}/judge/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Judge Score
         * @description 教师手工录入或修正成绩。
         *
         *     这是"解析器覆盖不到"的兜底出口。手工录入的记录会标记成 ``manual``，
         *     后续自动扫描**不会覆盖**它 —— 教师既然亲手改了，就该由教师负责。
         */
        put: operations["set_judge_score_api_v1_admin_contests__contest_id__judge_score_put"];
        post?: never;
        /** Clear Judge Score */
        delete: operations["clear_judge_score_api_v1_admin_contests__contest_id__judge_score_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contests/{contest_id}/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Players */
        get: operations["list_players_api_v1_admin_contests__contest_id__players_get"];
        put?: never;
        /**
         * Import Players
         * @description 批量导入/更新选手。按 ``player_no`` 幂等 upsert。
         */
        post: operations["import_players_api_v1_admin_contests__contest_id__players_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contests/{contest_id}/players/apply-roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Roster To Contest
         * @description 把名单应用到场次：名单里有而场次里没有的补上，已有的更新，默认不删人。
         *
         *     ``prune=True`` 时会删掉"名单里没有"的选手，但**有代码或成绩的一个都不动**，
         *     并在 ``protected`` 里列出来告诉教师"这些人删不掉、也不该删"。
         *
         *     名单是模板，场次是从它复制出去的独立数据 —— 这个动作是**显式**的，
         *     改了名单不会自动影响任何场次。
         */
        post: operations["apply_roster_to_contest_api_v1_admin_contests__contest_id__players_apply_roster_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contests/{contest_id}/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Problems */
        get: operations["list_problems_api_v1_admin_contests__contest_id__problems_get"];
        put?: never;
        /**
         * Import Problems
         * @description 批量登记/更新题目。按 ``ident`` 幂等 upsert —— 名单可以反复导。
         *
         *     单条不合法只跳过那一条并在 ``errors`` 里说明，不让整批失败 ——
         *     教师一次粘贴十道题，不该因为其中一个名字打错就全部白填。
         */
        post: operations["import_problems_api_v1_admin_contests__contest_id__problems_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contests/{contest_id}/problems/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Match Problem Path
         * @description 试算「这条相对路径会被算成哪道题」。
         *
         *     排错专用：教师配完模式想知道对不对，总得有个地方能问。放在服务端是因为
         *     **匹配只有一份实现** —— 前端自己算一遍，迟早会出现"界面说归 p1、
         *     实际归了 p2"这种谁也说不清的场面。
         *
         *     只做匹配，不碰文件系统；``path`` 按普通字符串处理，不需要是已存在的文件。
         */
        post: operations["match_problem_path_api_v1_admin_contests__contest_id__problems_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contests/{contest_id}/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Score Matrix
         * @description 「选手 × 题目」成绩矩阵。
         *
         *     **区分"0 分"和"没有成绩"**：``parse_status`` 为 ``missing`` 表示从未收到
         *     结果，``unparsed`` 表示收到了但看不懂。界面上这两者都不该显示成 0 ——
         *     那会让教师以为选手考砸了。
         *
         *     再往下还分一层：``missing`` 里要看清是**交了但还没评测**（``submitted``
         *     为真）还是**压根没交**。前者等着就行，后者得去问人 —— 教师看矩阵主要
         *     就是想知道哪几个座位该去催。
         */
        get: operations["score_matrix_api_v1_admin_contests__contest_id__scores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/deploys/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deploy */
        get: operations["get_deploy_api_v1_admin_deploys__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/deploys/{task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Deploy
         * @description 取消下发。
         *
         *     只把**未完成**的目标置为 cancelled —— 已经收下文件的机器不回滚。要求 Agent
         *     删掉已下发的文件是危险动作（可能误删教师自己放的文件），不做。
         */
        post: operations["cancel_deploy_api_v1_admin_deploys__task_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/deploys/{task_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Deploy
         * @description 把失败的目标重置为待下发，让 Agent 下一轮重新领取。
         */
        post: operations["retry_deploy_api_v1_admin_deploys__task_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_admin_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_admin_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_admin_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/players/{player_id}/enroll-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue Enroll Code
         * @description 签发（或重新签发）该选手的注册码。
         *
         *     注册码长期有效、可重复使用 —— 它是"机器凭据种子"，供快照还原后自愈。
         *     重新签发会吊销该选手此前所有未绑定的注册码。
         */
        post: operations["issue_enroll_code_api_v1_admin_players__player_id__enroll_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/problems/{problem_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Problem
         * @description 删除题目登记。
         *
         *     只删"清单里的一条"，**不动已有的成绩记录** —— 已经收到的评测结果不该因为
         *     清单调整而消失。那些成绩会以"未登记"的形式继续显示在矩阵里。
         */
        delete: operations["delete_problem_api_v1_admin_problems__problem_id__delete"];
        options?: never;
        head?: never;
        /** Update Problem */
        patch: operations["update_problem_api_v1_admin_problems__problem_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Releases */
        get: operations["list_releases_api_v1_admin_releases_get"];
        put?: never;
        /**
         * Upload Release
         * @description 上传 Agent 升级包。
         *
         *     **上传不等于铺开**：``published_at`` 保持为空，Agent 不会收到任何东西，
         *     直到教师显式调 rollout。上传一个包和把它推给 50 台机器是风险等级完全
         *     不同的两件事，不该合成一个动作。
         */
        post: operations["upload_release_api_v1_admin_releases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/releases/{release_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Release */
        patch: operations["update_release_api_v1_admin_releases__release_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/releases/{release_id}/rollout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rollout Release
         * @description 开始向 Agent 提供这个版本。
         *
         *     同一时刻只允许一个版本处于铺开状态 —— 否则不同机器可能拿到不同版本，
         *     排查问题时无法判断"这台机器到底跑的是哪个"。
         */
        post: operations["rollout_release_api_v1_admin_releases__release_id__rollout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/releases/{release_id}/yank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Yank Release
         * @description 撤回：不再向 Agent 提供该版本。
         *
         *     注意**撤回不能把已经升级的机器降回去** —— 那需要 Agent 侧的回滚机制
         *     （升级后连续启动失败会自动回滚）。撤回只是止血，防止影响面继续扩大。
         */
        post: operations["yank_release_api_v1_admin_releases__release_id__yank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/roster-entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Roster Entry */
        delete: operations["delete_roster_entry_api_v1_admin_roster_entries__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rosters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rosters */
        get: operations["list_rosters_api_v1_admin_rosters_get"];
        put?: never;
        /** Create Roster */
        post: operations["create_roster_api_v1_admin_rosters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rosters/{roster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Roster */
        get: operations["get_roster_api_v1_admin_rosters__roster_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Roster
         * @description 删除名单。
         *
         *     **只删名单本身，不动任何场次的选手。** 名单是模板，场次的参赛者是从它
         *     复制出去的一份独立数据 —— 删模板不该牵动已发生的比赛。引用了这份名单的
         *     场次会被置空（``ON DELETE SET NULL``），只是"没预设名单了"而已。
         */
        delete: operations["delete_roster_api_v1_admin_rosters__roster_id__delete"];
        options?: never;
        head?: never;
        /** Update Roster */
        patch: operations["update_roster_api_v1_admin_rosters__roster_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/rosters/{roster_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Roster Entries
         * @description 批量登记/更新名单条目。按 ``player_no`` 幂等 upsert。
         *
         *     和题目导入一样逐条容错：某一行不合法只跳过那一行并在 ``errors`` 里说明。
         *     一份名单几十上百行，因为一个空格全部白填是没人能接受的。
         */
        post: operations["import_roster_entries_api_v1_admin_rosters__roster_id__entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Asset */
        get: operations["download_asset_api_v1_agent_assets__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enroll
         * @description 用注册码换长期凭据。
         *
         *     刻意允许**重复注册**：NOI Linux 考试机常做整机快照还原，机器上的
         *     ``credential.json`` 会消失。此时 Agent 用镜像内置的注册码重新 enroll，
         *     服务端按 ``machine_id`` 认出这是老机器，换发新凭据并作废旧凭据。
         *     因此注册码不是一次性的，而是 "机器凭据种子"。
         */
        post: operations["enroll_api_v1_agent_enroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report Events
         * @description Agent 主动上报的审计事件（权限异常、磁盘满、批量重写等）。
         *
         *     刻意用列表批量提交：断网期间事件会堆积，逐条上报会在重连瞬间产生请求风暴。
         */
        post: operations["report_events_api_v1_agent_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File
         * @description 接收一个文件内容。
         *
         *     **旧版本保护**：若客户端送来的 ``sha256`` 与服务端台账当前记录的版本不一致，
         *     说明这是迟到的旧内容（断网补传、乱序重传），直接以 409 拒绝，让客户端在下一
         *     轮 tick 里拿到真正需要的版本。绝不覆盖更新的版本。
         */
        post: operations["upload_file_api_v1_agent_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["whoami_api_v1_agent_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/releases/{release_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Release
         * @description 下载 Agent 升级包。
         *
         *     只提供**已铺开且未撤回**的版本 —— 上传但未 rollout 的包对 Agent 不可见，
         *     这样"上传"和"铺开"的风险边界在服务端也是硬的，而不是只靠 Agent 自觉。
         */
        get: operations["download_release_api_v1_agent_releases__release_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/tick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tick */
        post: operations["tick_api_v1_agent_tick_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminInfo */
        AdminInfo: {
            /** Is Active */
            is_active: boolean;
            /** Username */
            username: string;
        };
        /** AgentEvent */
        AgentEvent: {
            /** Category */
            category: string;
            /**
             * Level
             * @default info
             */
            level: string;
            /** Message */
            message: string;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** AgentRuntimeOut */
        AgentRuntimeOut: {
            /** Agent Id */
            agent_id: number;
            /** Agent Version */
            agent_version?: string | null;
            /** Contest Id */
            contest_id: number;
            /**
             * Contest Slug
             * @default
             */
            contest_slug: string;
            /** Disk Free */
            disk_free?: number | null;
            /**
             * File Count
             * @default 0
             */
            file_count: number;
            /** Hostname */
            hostname?: string | null;
            /** Last Error */
            last_error?: string | null;
            /** Last Seen Ip */
            last_seen_ip?: string | null;
            /** Last Tick At */
            last_tick_at?: string | null;
            /** Machine Id */
            machine_id: string;
            /** Online */
            online: boolean;
            /** Player Id */
            player_id: number;
            /** Player Name */
            player_name?: string | null;
            /** Player No */
            player_no: string;
            /** Scan Root */
            scan_root?: string | null;
            /** Seconds Since Tick */
            seconds_since_tick?: number | null;
            /**
             * Tick Count
             * @default 0
             */
            tick_count: number;
        };
        /**
         * ApplyRosterIn
         * @description 把名单应用到场次。
         *
         *     ``prune`` 默认 **False**，而且**永远不动已经有代码或成绩的选手** ——
         *     名单调整是常事，把参赛者的提交一起删掉是不可逆的事故。
         */
        ApplyRosterIn: {
            /**
             * Prune
             * @default false
             */
            prune: boolean;
            /** Roster Id */
            roster_id?: number | null;
        };
        /** ApplyRosterOut */
        ApplyRosterOut: {
            /**
             * Created
             * @default 0
             */
            created: number;
            /**
             * Kept
             * @default 0
             */
            kept: number;
            /** Protected */
            protected?: string[];
            /**
             * Pruned
             * @default 0
             */
            pruned: number;
            /** Roster Id */
            roster_id?: number | null;
            /** Roster Name */
            roster_name?: string | null;
            /**
             * Updated
             * @default 0
             */
            updated: number;
        };
        /** AssetOut */
        AssetOut: {
            /** Contest Id */
            contest_id: number;
            /** Created At */
            created_at: string;
            /** Filename */
            filename: string;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
        };
        /** Body_upload_asset_api_v1_admin_contests__contest_id__assets_post */
        Body_upload_asset_api_v1_admin_contests__contest_id__assets_post: {
            /** File */
            file: string;
            /**
             * Kind
             * @default testdata
             */
            kind: string;
        };
        /** Body_upload_file_api_v1_agent_files_post */
        Body_upload_file_api_v1_agent_files_post: {
            /** File */
            file: string;
            /** Path */
            path: string;
            /** Sha256 */
            sha256: string;
        };
        /** Body_upload_release_api_v1_admin_releases_post */
        Body_upload_release_api_v1_admin_releases_post: {
            /**
             * Channel
             * @default stable
             */
            channel: string;
            /** File */
            file: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Version
             * @default
             */
            version: string;
        };
        /** ContestCreate */
        ContestCreate: {
            /** Default Roster Id */
            default_roster_id?: number | null;
            /** Enrollment Mode */
            enrollment_mode?: string | null;
            /** Name */
            name: string;
            /** Note */
            note?: string | null;
            /** Slug */
            slug?: string | null;
            /**
             * Status
             * @default draft
             */
            status: string;
        };
        /** ContestOut */
        ContestOut: {
            /** Created At */
            created_at: string;
            /** Default Roster Id */
            default_roster_id?: number | null;
            /** Default Roster Name */
            default_roster_name?: string | null;
            /**
             * Enrollment Mode
             * @default per_player_code
             */
            enrollment_mode: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Online Count
             * @default 0
             */
            online_count: number;
            /**
             * Player Count
             * @default 0
             */
            player_count: number;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
        };
        /**
         * ContestUpdate
         * @description 场次的可改字段。全部可选 —— 只改传了的。
         */
        ContestUpdate: {
            /**
             * Clear Default Roster
             * @default false
             */
            clear_default_roster: boolean;
            /** Default Roster Id */
            default_roster_id?: number | null;
            /** Enrollment Mode */
            enrollment_mode?: string | null;
            /** Name */
            name?: string | null;
            /** Note */
            note?: string | null;
            /** Status */
            status?: string | null;
        };
        /**
         * DeployCreate
         * @description 创建下发任务。
         *
         *     ``target_kind`` 取 ``all`` / ``player`` / ``group``：
         *     - ``all``    全量下发，忽略 ``player_ids``
         *     - ``player`` 只发给 ``player_ids`` 列出的选手
         *     - ``group``  发给 ``group_name`` 等于 ``target_group`` 的选手
         */
        DeployCreate: {
            /** Asset Id */
            asset_id: number;
            /**
             * Dest Dir
             * @default
             */
            dest_dir: string;
            /**
             * Mode
             * @default overwrite
             */
            mode: string;
            /** Player Ids */
            player_ids?: number[];
            /** Target Group */
            target_group?: string | null;
            /**
             * Target Kind
             * @default all
             */
            target_kind: string;
        };
        /** DeployJob */
        DeployJob: {
            /** Asset Id */
            asset_id: number;
            /** Dest */
            dest: string;
            /**
             * Mode
             * @default overwrite
             */
            mode: string;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
            /** Url */
            url: string;
        };
        /** DeployTargetOut */
        DeployTargetOut: {
            /**
             * Bytes Done
             * @default 0
             */
            bytes_done: number;
            /** Last Error */
            last_error?: string | null;
            /** Player Id */
            player_id: number;
            /** Player No */
            player_no: string;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /** Status */
            status: string;
        };
        /** DeployTaskOut */
        DeployTaskOut: {
            /** Asset Id */
            asset_id: number;
            /** Contest Id */
            contest_id: number;
            /** Created At */
            created_at: string;
            /** Dest Dir */
            dest_dir: string;
            /**
             * Done
             * @default 0
             */
            done: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /** Filename */
            filename: string;
            /** Id */
            id: number;
            /** Mode */
            mode: string;
            /**
             * Pending
             * @default 0
             */
            pending: number;
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
            /** Status */
            status: string;
            /** Target Kind */
            target_kind: string;
            /** Targets */
            targets?: components["schemas"]["DeployTargetOut"][];
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** EnrollCodeOut */
        EnrollCodeOut: {
            /** Code */
            code: string;
            /** Expires At */
            expires_at?: string | null;
            /** Note */
            note?: string | null;
            /** Player Id */
            player_id: number;
            /** Player No */
            player_no: string;
        };
        /** EnrollRequest */
        EnrollRequest: {
            /** Agent Version */
            agent_version?: string | null;
            /** Enroll Code */
            enroll_code: string;
            /** Hostname */
            hostname?: string | null;
            /** Machine Id */
            machine_id: string;
            /** Os Info */
            os_info?: string | null;
        };
        /** EnrollResponse */
        EnrollResponse: {
            /** Agent Id */
            agent_id: number;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Contest Id */
            contest_id: number;
            /** Contest Name */
            contest_name: string;
            /** Contest Slug */
            contest_slug: string;
            /** Player Name */
            player_name?: string | null;
            /** Player No */
            player_no: string;
            /** Token */
            token: string;
        };
        /** EventOut */
        EventOut: {
            /** Category */
            category: string;
            /** Id */
            id: number;
            /** Level */
            level: string;
            /** Message */
            message: string;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
            /** Player No */
            player_no?: string | null;
            /** Ts */
            ts: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JudgeRunOut */
        JudgeRunOut: {
            /** Detail */
            detail?: string | null;
            /** Id */
            id: number;
            /** Max Score */
            max_score?: number | null;
            /** Parse Status */
            parse_status: string;
            /** Player Id */
            player_id: number;
            /** Player No */
            player_no: string;
            /** Problem */
            problem: string;
            /** Score */
            score?: number | null;
            /** Source Path */
            source_path?: string | null;
            /** Status */
            status?: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** JudgeScanOut */
        JudgeScanOut: {
            /** Errors */
            errors?: string[];
            /**
             * Manual
             * @default 0
             */
            manual: number;
            /**
             * Parsed
             * @default 0
             */
            parsed: number;
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
            /**
             * Unchanged
             * @default 0
             */
            unchanged: number;
            /**
             * Unparsed
             * @default 0
             */
            unparsed: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Expires At */
            expires_at: string;
            /** Token */
            token: string;
            /** Username */
            username: string;
        };
        /**
         * ManualScoreIn
         * @description 教师手工录入 / 修正成绩。
         *
         *     未解析的文件靠它兜底 —— 我们无法覆盖所有评测器格式，但绝不能因此让教师
         *     只能干瞪眼。
         */
        ManualScoreIn: {
            /** Max Score */
            max_score?: number | null;
            /** Player Id */
            player_id: number;
            /** Problem */
            problem: string;
            /** Score */
            score?: number | null;
            /** Status */
            status?: string | null;
        };
        /**
         * PartialDownload
         * @description 客户端本地未完成的下载，服务端据此回填 offset。
         */
        PartialDownload: {
            /** Asset Id */
            asset_id: number;
            /** Bytes Done */
            bytes_done: number;
        };
        /** PlayerOut */
        PlayerOut: {
            /** Contest Id */
            contest_id: number;
            /**
             * File Count
             * @default 0
             */
            file_count: number;
            /** Group Name */
            group_name?: string | null;
            /**
             * Has Agent
             * @default false
             */
            has_agent: boolean;
            /** Id */
            id: number;
            /** Last Tick At */
            last_tick_at?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Online
             * @default false
             */
            online: boolean;
            /** Player No */
            player_no: string;
            /** Seat */
            seat?: string | null;
        };
        /** PlayerUpsert */
        PlayerUpsert: {
            /** Group Name */
            group_name?: string | null;
            /** Name */
            name?: string | null;
            /** Player No */
            player_no: string;
            /** Seat */
            seat?: string | null;
        };
        /**
         * ProblemColumnOut
         * @description 成绩矩阵的一列。
         *
         *     ``declared=False`` 表示这个题目**只在评测结果里出现过，没在题目清单里登记**。
         *     仍然显示出来，避免因为漏登记而丢掉真实成绩；界面上应当标注提醒教师去补登记。
         */
        ProblemColumnOut: {
            /**
             * Declared
             * @default true
             */
            declared: boolean;
            /** Ident */
            ident: string;
            /** Title */
            title?: string | null;
        };
        /** ProblemImportOut */
        ProblemImportOut: {
            /**
             * Created
             * @default 0
             */
            created: number;
            /** Errors */
            errors?: string[];
            /** Problems */
            problems?: components["schemas"]["ProblemOut"][];
            /**
             * Updated
             * @default 0
             */
            updated: number;
        };
        /**
         * ProblemMatchIn
         * @description 拿一条相对路径来试算归题结果。
         *
         *     界面上的「这条路径会算成哪道题」走的是**服务端同一套匹配代码** ——
         *     前端再实现一遍 glob 迟早会和服务端说不到一块去，而教师没法判断
         *     是配置错了还是界面显示错了。
         */
        ProblemMatchIn: {
            /** Path */
            path: string;
        };
        /** ProblemMatchOut */
        ProblemMatchOut: {
            /** Expanded */
            expanded?: string[];
            /** Path */
            path: string;
            /** Patterns */
            patterns?: string[];
            /** Problem */
            problem?: string | null;
        };
        /** ProblemOut */
        ProblemOut: {
            /** Contest Id */
            contest_id: number;
            /** File Patterns */
            file_patterns?: string[];
            /** Id */
            id: number;
            /** Ident */
            ident: string;
            /** Note */
            note?: string | null;
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
            /** Title */
            title?: string | null;
        };
        /**
         * ProblemUpsert
         * @description 登记一道题。
         *
         *     ``ident`` 会同时成为目录名、代码文件名与成绩矩阵的列名，
         *     所以要按路径段的规则校验（服务端会做）。
         *
         *     ``file_patterns`` 是用于把回收的代码归到这道题的 glob 模式。
         *     留空表示用服务端的默认模式（出厂值 ``{ident}/**``）。
         */
        ProblemUpsert: {
            /** File Patterns */
            file_patterns?: string[];
            /** Ident */
            ident: string;
            /** Note */
            note?: string | null;
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
            /** Title */
            title?: string | null;
        };
        /** ReleaseOut */
        ReleaseOut: {
            /** Channel */
            channel: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: number;
            /** Key Id */
            key_id?: string | null;
            /** Notes */
            notes?: string | null;
            /** Published At */
            published_at?: string | null;
            /**
             * Rolled Out
             * @default false
             */
            rolled_out: boolean;
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
            /** Version */
            version: string;
            /**
             * Yanked
             * @default false
             */
            yanked: boolean;
        };
        /** ReleaseUpdate */
        ReleaseUpdate: {
            /** Channel */
            channel?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** RosterCreate */
        RosterCreate: {
            /** Name */
            name: string;
            /** Note */
            note?: string | null;
        };
        /** RosterDetailOut */
        RosterDetailOut: {
            /** Created At */
            created_at: string;
            /** Entries */
            entries?: components["schemas"]["RosterEntryOut"][];
            /**
             * Entry Count
             * @default 0
             */
            entry_count: number;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Note */
            note?: string | null;
        };
        /**
         * RosterEntryIn
         * @description 名单条目。
         *
         *     ``player_no`` 的长度上限刻意给得**很宽**（512），真正的 64 字上限由业务层
         *     逐条判定。原因：pydantic 的校验是**全有或全无** —— 一条超长会让整个请求
         *     422，教师粘的 100 行名单全部白填，而界面上只会弹一句
         *     "String should have at most 64 characters"。
         *
         *     批量接口的逐条错误必须由业务层报，那里才能做到"跳过这一条，其余照常入库"。
         *     这里留的宽上限只用来挡住明显荒谬的输入（比如 10MB 的字符串）。
         */
        RosterEntryIn: {
            /** Group Name */
            group_name?: string | null;
            /** Name */
            name?: string | null;
            /** Player No */
            player_no: string;
            /** Seat */
            seat?: string | null;
        };
        /** RosterEntryOut */
        RosterEntryOut: {
            /** Group Name */
            group_name?: string | null;
            /** Id */
            id: number;
            /** Name */
            name?: string | null;
            /** Player No */
            player_no: string;
            /** Roster Id */
            roster_id: number;
            /** Seat */
            seat?: string | null;
        };
        /**
         * RosterImportOut
         * @description 名单导入结果。
         *
         *     和题目导入一样**逐条容错**：某一行不合法只跳过那一行并在 ``errors``
         *     里说明，不让整批失败。一份名单几十上百行，因为一个空格全部白填
         *     是没人能接受的。
         */
        RosterImportOut: {
            /**
             * Created
             * @default 0
             */
            created: number;
            /** Entries */
            entries?: components["schemas"]["RosterEntryOut"][];
            /** Errors */
            errors?: string[];
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
            /**
             * Updated
             * @default 0
             */
            updated: number;
        };
        /** RosterOut */
        RosterOut: {
            /** Created At */
            created_at: string;
            /**
             * Entry Count
             * @default 0
             */
            entry_count: number;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Note */
            note?: string | null;
        };
        /**
         * ScanEntry
         * @description 一条扫描结果。**不含文件内容**，只有索引。
         */
        ScanEntry: {
            /** Mtime */
            mtime: number;
            /** Path */
            path: string;
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
        };
        /** ScoreCellOut */
        ScoreCellOut: {
            /** Detail */
            detail?: string | null;
            /** Max Score */
            max_score?: number | null;
            /**
             * Parse Status
             * @default missing
             */
            parse_status: string;
            /** Problem */
            problem: string;
            /** Score */
            score?: number | null;
            /** Status */
            status?: string | null;
            /**
             * Submitted
             * @default false
             */
            submitted: boolean;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ScoreMatrixOut */
        ScoreMatrixOut: {
            /** Columns */
            columns?: components["schemas"]["ProblemColumnOut"][];
            /**
             * Complete
             * @default true
             */
            complete: boolean;
            /** Contest Id */
            contest_id: number;
            /** Rows */
            rows?: components["schemas"]["ScoreRowOut"][];
            /**
             * Unparsed
             * @default 0
             */
            unparsed: number;
        };
        /** ScoreRowOut */
        ScoreRowOut: {
            /** Cells */
            cells?: components["schemas"]["ScoreCellOut"][];
            /** Player Id */
            player_id: number;
            /** Player Name */
            player_name?: string | null;
            /** Player No */
            player_no: string;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** SimpleAck */
        SimpleAck: {
            /** Detail */
            detail?: string | null;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** SourceFileOut */
        SourceFileOut: {
            /** Content Stored */
            content_stored: boolean;
            /** Deleted At */
            deleted_at?: string | null;
            /** First Seen At */
            first_seen_at: string;
            /** Id */
            id: number;
            /** Last Seen At */
            last_seen_at: string;
            /** Player Id */
            player_id: number;
            /** Player No */
            player_no: string;
            /** Problem */
            problem?: string | null;
            /** Rel Path */
            rel_path: string;
            /** Revision */
            revision: number;
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
        };
        /** TickRequest */
        TickRequest: {
            /** Agent Version */
            agent_version?: string | null;
            /** Completed Assets */
            completed_assets?: number[];
            /** Machine Id */
            machine_id: string;
            /** Partials */
            partials?: components["schemas"]["PartialDownload"][];
            /** Scan */
            scan?: components["schemas"]["ScanEntry"][];
            /**
             * Scan Complete
             * @default true
             */
            scan_complete: boolean;
            /** Scan Root */
            scan_root?: string | null;
            stats?: components["schemas"]["TickStats"];
            /** Ts */
            ts: number;
        };
        /** TickResponse */
        TickResponse: {
            /** Cancel Assets */
            cancel_assets?: number[];
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Deploy Jobs */
            deploy_jobs?: components["schemas"]["DeployJob"][];
            /** Need Upload */
            need_upload?: string[];
            /** Next Tick Seconds */
            next_tick_seconds: number;
            /** Server Time */
            server_time: number;
            upgrade?: components["schemas"]["UpgradeInfo"] | null;
        };
        /** TickStats */
        TickStats: {
            /** Disk Free */
            disk_free?: number | null;
            /** Last Error */
            last_error?: string | null;
            /**
             * Queue
             * @default 0
             */
            queue: number;
        };
        /** UpgradeInfo */
        UpgradeInfo: {
            /** Notes */
            notes?: string | null;
            /** Sha256 */
            sha256: string;
            /** Signature */
            signature: string;
            /**
             * Size
             * @default 0
             */
            size: number;
            /** Url */
            url: string;
            /** Version */
            version: string;
        };
        /**
         * UpgradeStatusOut
         * @description 自更新总览。教师一眼看清"现在会不会有机器被升级"。
         */
        UpgradeStatusOut: {
            active_release?: components["schemas"]["ReleaseOut"] | null;
            /** Error */
            error?: string | null;
            /** Key Id */
            key_id?: string | null;
            /** Releases */
            releases?: components["schemas"]["ReleaseOut"][];
            /** Signing Available */
            signing_available: boolean;
        };
        /** UploadResult */
        UploadResult: {
            /** Path */
            path: string;
            /** Revision */
            revision: number;
            /** Sha256 */
            sha256: string;
            /** Stored */
            stored: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_contests_api_v1_admin_contests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContestOut"][];
                };
            };
        };
    };
    create_contest_api_v1_admin_contests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contest_api_v1_admin_contests__contest_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContestUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agents_api_v1_admin_contests__contest_id__agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRuntimeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assets_api_v1_admin_contests__contest_id__assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_asset_api_v1_admin_contests__contest_id__assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_asset_api_v1_admin_contests__contest_id__assets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deploys_api_v1_admin_contests__contest_id__deploys_get: {
        parameters: {
            query?: {
                include_targets?: boolean;
            };
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeployTaskOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_deploy_api_v1_admin_contests__contest_id__deploys_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeployCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeployTaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_admin_contests__contest_id__events_get: {
        parameters: {
            query?: {
                limit?: number;
                category?: string | null;
            };
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_api_v1_admin_contests__contest_id__files_get: {
        parameters: {
            query?: {
                player_id?: number | null;
                include_deleted?: boolean;
                limit?: number;
            };
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFileOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescan_judge_results_api_v1_admin_contests__contest_id__judge_rescan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JudgeScanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_judge_runs_api_v1_admin_contests__contest_id__judge_runs_get: {
        parameters: {
            query?: {
                parse_status?: string | null;
            };
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JudgeRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_judge_score_api_v1_admin_contests__contest_id__judge_score_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualScoreIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JudgeRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_judge_score_api_v1_admin_contests__contest_id__judge_score_delete: {
        parameters: {
            query: {
                player_id: number;
                problem: string;
            };
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_players_api_v1_admin_contests__contest_id__players_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_players_api_v1_admin_contests__contest_id__players_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerUpsert"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_roster_to_contest_api_v1_admin_contests__contest_id__players_apply_roster_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRosterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyRosterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_problems_api_v1_admin_contests__contest_id__problems_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_problems_api_v1_admin_contests__contest_id__problems_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProblemUpsert"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_problem_path_api_v1_admin_contests__contest_id__problems_match_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProblemMatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemMatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_matrix_api_v1_admin_contests__contest_id__scores_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreMatrixOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deploy_api_v1_admin_deploys__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeployTaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_deploy_api_v1_admin_deploys__task_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_deploy_api_v1_admin_deploys__task_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_admin_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    login_api_v1_admin_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_admin_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleAck"];
                };
            };
        };
    };
    me_api_v1_admin_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminInfo"];
                };
            };
        };
    };
    issue_enroll_code_api_v1_admin_players__player_id__enroll_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollCodeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_problem_api_v1_admin_problems__problem_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_problem_api_v1_admin_problems__problem_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProblemUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_releases_api_v1_admin_releases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpgradeStatusOut"];
                };
            };
        };
    };
    upload_release_api_v1_admin_releases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_release_api_v1_admin_releases_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_release_api_v1_admin_releases__release_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                release_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollout_release_api_v1_admin_releases__release_id__rollout_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                release_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    yank_release_api_v1_admin_releases__release_id__yank_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                release_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_roster_entry_api_v1_admin_roster_entries__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rosters_api_v1_admin_rosters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterOut"][];
                };
            };
        };
    };
    create_roster_api_v1_admin_rosters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RosterCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_roster_api_v1_admin_rosters__roster_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roster_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_roster_api_v1_admin_rosters__roster_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roster_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_roster_api_v1_admin_rosters__roster_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roster_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RosterCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_roster_entries_api_v1_admin_rosters__roster_id__entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roster_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RosterEntryIn"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_asset_api_v1_agent_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enroll_api_v1_agent_enroll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_events_api_v1_agent_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentEvent"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_api_v1_agent_files_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_v1_agent_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whoami_api_v1_agent_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    download_release_api_v1_agent_releases__release_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                release_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tick_api_v1_agent_tick_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TickRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
